#build image
FROM openbankingnigeria/alpine-oraclejdk8:slim AS build

ARG BASE_SRC_PATH="/sandbox/apicockpit"
ARG WEB_APP_PATH=$BASE_SRC_PATH"/src/main/webapp"

RUN apk update && apk upgrade && \
    apk add --no-cache bash git maven

RUN git clone https://github.com/openbankingnigeria/sandbox.git

#remove the web app but leave swagger-ui
RUN rm -rf $BASE_SRC_PATH/src/test && \
    cd $WEB_APP_PATH/app && \
    find -maxdepth 1 ! -name "polyfills.ts" -exec rm -rv {} \; && \
    touch $WEB_APP_PATH/app/app.main.ts

RUN sh -c "mvn clean install -q -Dmaven.test.skip=true -f/sandbox/utils/pom.xml" && \
    sh -c "mvn clean package -Dmaven.test.skip=true -f$BASE_SRC_PATH/pom.xml"

# final image
FROM openjdk:8-jre-alpine

ENV SPRING_OUTPUT_ANSI_ENABLED=ALWAYS \
    JAVA_OPTS=""

#Add obn user to run start app
RUN adduser -D -s /bin/sh obn
WORKDIR /home/obn

COPY --from=build /sandbox/apicockpit/target/cockpit-0.0.1-SNAPSHOT.war /home/obn/app.war

USER root
RUN chown -R obn:obn /home/obn

USER obn

ENTRYPOINT [ "sh", "-c", "java $JAVA_OPTS -Djava.security.egd=file:/dev/./urandom -jar $HOME/app.war" ]

EXPOSE 8081
