#build image
FROM frolvlad/alpine-oraclejdk8:slim AS build


RUN apk update && apk upgrade && \
    apk add --no-cache bash git openssh maven

RUN git clone https://github.com/openbankingnigeria/sandbox.git

RUN sh -c "mvn clean install -Dmaven.test.skip=true -f/sandbox/utils/pom.xml" && \
    sh -c "mvn clean package -Dmaven.test.skip=true -P\!webpack -f/sandbox/apicockpit/pom.xml"

# final image
FROM openjdk:8-jre-alpine

ENV SPRING_OUTPUT_ANSI_ENABLED=ALWAYS \
    JAVA_OPTS=""

#Add obn user to run start app
RUN adduser -D -s /bin/sh obn
WORKDIR /home/obn

COPY --from=build /sandbox/apicockpit/target/cockpit-0.0.1-SNAPSHOT.war /home/obn/app.war

USER root
RUN chown -R obn:obn /home/obn

USER obn

ENTRYPOINT [ "sh", "-c", "java $JAVA_OPTS -Djava.security.egd=file:/dev/./urandom -jar $HOME/app.war" ]

EXPOSE 8081
